### ISSUE TITLE
How to adjust the fillrandom mode "Bulkload" and "Normal"?

### ISSUE THREAD

**Issue by SSK015** [ruihong123/dLSM#1]
I have enabled your code on my servers connected by RDMA network. I want to know **how to adjust the fillrandom mode "Bulkload" and "Normal"**? I notice that you mention it in your paper and the repo's README.md.

**Comment by SSK015** [comment]
Maybe this parameter? static const int kL0_StopWritesTrigger = 32;
How can I switch to bulkload mode?

**Comment by ruihong123** [comment]
Just set it as an extremely large parameter. E.g. 65535
